### ISSUE TITLE
Написать unit-тесты для скрипта

### ISSUE THREAD

**Issue by gagask** [moevm/MSE-2023-moevm-doku_wiki-10#12]

**Comment by gagask** [comment]
Для каждой фичи создать файл с таблицей и ее соответствием в dokuWiki формате.

**Comment by ZhenjaMax** [comment]
Описали в устной форме причину невозможности сделать корректные тесты.

**Comment by forest-chan** [comment]
Код библиотек был изменен таким образом, что из него ничего не экпортируется, т.е. нет module exports и export default. 
Для того чтобы получить доступ к нужным функциям и объектам внутри тестов, необходимо  экспортировать функции и глобальные переменные (библиотеки). В таком случае, нам приходится изменять уже переписанный код библиотек и файла script.js. Таким образом получается, импортировать необходимые функции и библиотеки в файлы тестов, однако в самих функциях используется работа с браузерным окружением и jquery (FileReader, document, etc), которое не получается имитировать.
Ошибка 1:
![error1](https://github.com/moevm/MSE-2023-moevm-doku_wiki-10/assets/71666648/e06cbc78-9ca0-4bff-82fd-19787ee3cee2)
Ошибка 2:
![error2](https://github.com/moevm/MSE-2023-moevm-doku_wiki-10/assets/71666648/d855f1da-6757-4b4f-9f85-c0f5b75a7455)
Код библиотек:
![libraries-code](https://github.com/moevm/MSE-2023-moevm-doku_wiki-10/assets/71666648/5dbf430c-14d7-4ece-ad6a-7f332670d873)
Скрипт, подключаемый Dokuwiki
![main-script](https://github.com/moevm/MSE-2023-moevm-doku_wiki-10/assets/71666648/b86673f1-ded9-40b6-a43d-e8bb2bf1a266)

**Comment by forest-chan** [comment]
The library code has been changed in such a way that nothing is exported from it, i.e. no module exports and export default.
In order to get access to the necessary functions and objects inside tests, it is necessary to export functions and global variables (libraries). In this case, we have to change the already rewritten code of the libraries and the script.js file. Thus, it turns out to import the necessary functions and libraries into the test files, however, the functions themselves use the work with the browser environment and jquery (FileReader, document, etc), which cannot be imitated.
Error 1:
![error1](https://github.com/moevm/MSE-2023-moevm-doku_wiki-10/assets/71666648/70787392-464f-4826-9325-80345a09f218)

Error 2:
![error2](https://github.com/moevm/MSE-2023-moevm-doku_wiki-10/assets/71666648/91417637-935d-4be0-9f05-891284834838)

Libraries code:
![libraries-code](https://github.com/moevm/MSE-2023-moevm-doku_wiki-10/assets/71666648/4485ce59-2918-43f6-83f9-dc9960bf0a08)

script.js for DokuWiki plugin:
![main-script](https://github.com/moevm/MSE-2023-moevm-doku_wiki-10/assets/71666648/e9d265db-a26a-4800-a8a2-ba4f1f836033)
